# Welcome to Serverless!
service: pictures-identifier-control

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectLabels
      Resource: '*'
    - Effect: Allow
      Action:
        - translate:TranslateText
      Resource: '*'

functions:
  - ${file(functions.yml)}
